# Generated by Django 5.1.2 on 2024-10-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
