# Generated by Django 5.1.2 on 2024-10-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20241025_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
    ]
