# Generated by Django 5.1.2 on 2024-10-27 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_document_patient'),
        ('patients', '0006_userpatientassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient'),
        ),
    ]
