# Generated by Django 5.1.2 on 2024-10-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_document_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_uploaded_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
