# Generated by Django 5.1.2 on 2024-10-30 02:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_remove_treatmentrecord_assigned_nurses_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentrecord',
            name='assigned_nurses',
            field=models.ManyToManyField(related_name='assigned_nurses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='num_of_nurses',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='NurseAssignment',
        ),
    ]
