# Generated by Django 5.1.2 on 2024-10-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_treatmentrecord_assigned_nurses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='treated_by',
        ),
        migrations.DeleteModel(
            name='TreatmentRecord',
        ),
    ]
